#!/bin/bash

PROJECT_ID=`gcloud config get-value core/project`

if [ "$PROJECT_ID" == "" ]; then
    echo "Needs project id"
    exit 1
fi

set -ex

(cd ../.. && rm -r dist && python setup.py sdist)
cp ../../dist/kubeque-*.tar.gz kubeque-0.2.tar.gz
docker build . -t us.gcr.io/$PROJECT_ID/kubeque-example
gcloud docker -- push us.gcr.io/$PROJECT_ID/kubeque-example
