#!/bin/bash

PROJECT_ID=`gcloud config get-value core/project`

if [ "$PROJECT_ID" == "" ]; then
    echo "Needs project id"
    exit 1
fi

set -ex

# TODO check first for python3 and use that if it exists
PYTHONEXE=`which python3`
if [ "$PYTHONEXE" = "" ]; then
  PYTHONEXE=python
fi

(cd ../.. && rm -rf dist && $PYTHONEXE setup.py sdist)
cp ../../dist/kubeque-*.tar.gz .
docker build . -t us.gcr.io/$PROJECT_ID/kubeque-example
gcloud docker -- push us.gcr.io/$PROJECT_ID/kubeque-example
