#!/usr/bin/env python

DELAY=5

import sys
import time
from datetime import datetime
print("running")
with open("output.txt", "w") as fd:
    fd.write("Starting at {}\n".format(str(datetime.now())))
    fd.write("args were: {}\n".format(sys.argv))
    time.sleep(DELAY)
    fd.write("Finished at {}\n".format(str(datetime.now())))
print("done")


