# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pb.proto
# Protobuf Python Version: 5.29.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 2, "", "pb.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x08pb.proto"A\n\x11ReadOutputRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x03"E\n\x0fReadOutputReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tendOfFile\x18\x02 \x01(\x08\x12\x11\n\tnewOffset\x18\x03 \x01(\x03"\x19\n\x17GetProcessStatusRequest"\xbe\x02\n\x15GetProcessStatusReply\x12\x14\n\x0cprocessCount\x18\x01 \x01(\x05\x12\x13\n\x0btotalMemory\x18\x02 \x01(\x03\x12\x11\n\ttotalData\x18\x03 \x01(\x03\x12\x13\n\x0btotalShared\x18\x04 \x01(\x03\x12\x15\n\rtotalResident\x18\x05 \x01(\x03\x12\x0f\n\x07\x63puUser\x18\x06 \x01(\x03\x12\x11\n\tcpuSystem\x18\x07 \x01(\x03\x12\x0f\n\x07\x63puIdle\x18\x08 \x01(\x03\x12\x11\n\tcpuIowait\x18\t \x01(\x03\x12\x10\n\x08memTotal\x18\n \x01(\x03\x12\x14\n\x0cmemAvailable\x18\x0b \x01(\x03\x12\x0f\n\x07memFree\x18\x0c \x01(\x03\x12\x1c\n\x14memPressureSomeAvg10\x18\r \x01(\x05\x12\x1c\n\x14memPressureFullAvg10\x18\x0e \x01(\x05\x32\x87\x01\n\x07Monitor\x12\x34\n\nReadOutput\x12\x12.ReadOutputRequest\x1a\x10.ReadOutputReply"\x00\x12\x46\n\x10GetProcessStatus\x12\x18.GetProcessStatusRequest\x1a\x16.GetProcessStatusReply"\x00\x42\x06Z\x04./pbb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pb_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\004./pb"
    _globals["_READOUTPUTREQUEST"]._serialized_start = 12
    _globals["_READOUTPUTREQUEST"]._serialized_end = 77
    _globals["_READOUTPUTREPLY"]._serialized_start = 79
    _globals["_READOUTPUTREPLY"]._serialized_end = 148
    _globals["_GETPROCESSSTATUSREQUEST"]._serialized_start = 150
    _globals["_GETPROCESSSTATUSREQUEST"]._serialized_end = 175
    _globals["_GETPROCESSSTATUSREPLY"]._serialized_start = 178
    _globals["_GETPROCESSSTATUSREPLY"]._serialized_end = 496
    _globals["_MONITOR"]._serialized_start = 499
    _globals["_MONITOR"]._serialized_end = 634
# @@protoc_insertion_point(module_scope)
