# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kubeque/pb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kubeque/pb.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x10kubeque/pb.proto\"A\n\x11ReadOutputRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x03\"2\n\x0fReadOutputReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tendOfFile\x18\x02 \x01(\x08\x32?\n\x07Monitor\x12\x34\n\nReadOutput\x12\x12.ReadOutputRequest\x1a\x10.ReadOutputReply\"\x00\x62\x06proto3')
)




_READOUTPUTREQUEST = _descriptor.Descriptor(
  name='ReadOutputRequest',
  full_name='ReadOutputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='ReadOutputRequest.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='ReadOutputRequest.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='ReadOutputRequest.offset', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=85,
)


_READOUTPUTREPLY = _descriptor.Descriptor(
  name='ReadOutputReply',
  full_name='ReadOutputReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ReadOutputReply.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endOfFile', full_name='ReadOutputReply.endOfFile', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['ReadOutputRequest'] = _READOUTPUTREQUEST
DESCRIPTOR.message_types_by_name['ReadOutputReply'] = _READOUTPUTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadOutputRequest = _reflection.GeneratedProtocolMessageType('ReadOutputRequest', (_message.Message,), dict(
  DESCRIPTOR = _READOUTPUTREQUEST,
  __module__ = 'kubeque.pb_pb2'
  # @@protoc_insertion_point(class_scope:ReadOutputRequest)
  ))
_sym_db.RegisterMessage(ReadOutputRequest)

ReadOutputReply = _reflection.GeneratedProtocolMessageType('ReadOutputReply', (_message.Message,), dict(
  DESCRIPTOR = _READOUTPUTREPLY,
  __module__ = 'kubeque.pb_pb2'
  # @@protoc_insertion_point(class_scope:ReadOutputReply)
  ))
_sym_db.RegisterMessage(ReadOutputReply)



_MONITOR = _descriptor.ServiceDescriptor(
  name='Monitor',
  full_name='Monitor',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=139,
  serialized_end=202,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReadOutput',
    full_name='Monitor.ReadOutput',
    index=0,
    containing_service=None,
    input_type=_READOUTPUTREQUEST,
    output_type=_READOUTPUTREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONITOR)

DESCRIPTOR.services_by_name['Monitor'] = _MONITOR

# @@protoc_insertion_point(module_scope)
