# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparklespray/pb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x15sparklespray/pb.proto"A\n\x11ReadOutputRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x03"E\n\x0fReadOutputReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tendOfFile\x18\x02 \x01(\x08\x12\x11\n\tnewOffset\x18\x03 \x01(\x03"\x19\n\x17GetProcessStatusRequest"\x81\x01\n\x15GetProcessStatusReply\x12\x14\n\x0cprocessCount\x18\x01 \x01(\x05\x12\x13\n\x0btotalMemory\x18\x02 \x01(\x03\x12\x11\n\ttotalData\x18\x03 \x01(\x03\x12\x13\n\x0btotalShared\x18\x04 \x01(\x03\x12\x15\n\rtotalResident\x18\x05 \x01(\x03\x32\x87\x01\n\x07Monitor\x12\x34\n\nReadOutput\x12\x12.ReadOutputRequest\x1a\x10.ReadOutputReply"\x00\x12\x46\n\x10GetProcessStatus\x12\x18.GetProcessStatusRequest\x1a\x16.GetProcessStatusReply"\x00\x42\x06Z\x04./pbb\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "sparklespray.pb_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z\004./pb"
    _READOUTPUTREQUEST._serialized_start = 25
    _READOUTPUTREQUEST._serialized_end = 90
    _READOUTPUTREPLY._serialized_start = 92
    _READOUTPUTREPLY._serialized_end = 161
    _GETPROCESSSTATUSREQUEST._serialized_start = 163
    _GETPROCESSSTATUSREQUEST._serialized_end = 188
    _GETPROCESSSTATUSREPLY._serialized_start = 191
    _GETPROCESSSTATUSREPLY._serialized_end = 320
    _MONITOR._serialized_start = 323
    _MONITOR._serialized_end = 458
# @@protoc_insertion_point(module_scope)
