"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class ReadOutputRequest(google.protobuf.message.Message):
    """The request message containing the user's name."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASKID_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    taskId: builtins.str
    size: builtins.int
    offset: builtins.int
    def __init__(
        self,
        *,
        taskId: builtins.str = ...,
        size: builtins.int = ...,
        offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "offset", b"offset", "size", b"size", "taskId", b"taskId"
        ],
    ) -> None: ...

global___ReadOutputRequest = ReadOutputRequest

@typing_extensions.final
class ReadOutputReply(google.protobuf.message.Message):
    """The response message containing the greetings"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    ENDOFFILE_FIELD_NUMBER: builtins.int
    NEWOFFSET_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    endOfFile: builtins.bool
    newOffset: builtins.int
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        endOfFile: builtins.bool = ...,
        newOffset: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "data", b"data", "endOfFile", b"endOfFile", "newOffset", b"newOffset"
        ],
    ) -> None: ...

global___ReadOutputReply = ReadOutputReply

@typing_extensions.final
class GetProcessStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetProcessStatusRequest = GetProcessStatusRequest

@typing_extensions.final
class GetProcessStatusReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROCESSCOUNT_FIELD_NUMBER: builtins.int
    TOTALMEMORY_FIELD_NUMBER: builtins.int
    TOTALDATA_FIELD_NUMBER: builtins.int
    TOTALSHARED_FIELD_NUMBER: builtins.int
    TOTALRESIDENT_FIELD_NUMBER: builtins.int
    processCount: builtins.int
    totalMemory: builtins.int
    totalData: builtins.int
    totalShared: builtins.int
    totalResident: builtins.int
    def __init__(
        self,
        *,
        processCount: builtins.int = ...,
        totalMemory: builtins.int = ...,
        totalData: builtins.int = ...,
        totalShared: builtins.int = ...,
        totalResident: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "processCount",
            b"processCount",
            "totalData",
            b"totalData",
            "totalMemory",
            b"totalMemory",
            "totalResident",
            b"totalResident",
            "totalShared",
            b"totalShared",
        ],
    ) -> None: ...

global___GetProcessStatusReply = GetProcessStatusReply
