"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class ReadOutputRequest(google.protobuf.message.Message):
    """The request message containing the user's name."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TASKID_FIELD_NUMBER: builtins.int
    SIZE_FIELD_NUMBER: builtins.int
    OFFSET_FIELD_NUMBER: builtins.int
    taskId: builtins.str
    size: builtins.int
    offset: builtins.int
    def __init__(
        self,
        *,
        taskId: builtins.str = ...,
        size: builtins.int = ...,
        offset: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "offset", b"offset", "size", b"size", "taskId", b"taskId"
        ],
    ) -> None: ...

global___ReadOutputRequest = ReadOutputRequest

@typing.final
class ReadOutputReply(google.protobuf.message.Message):
    """The response message containing the greetings"""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DATA_FIELD_NUMBER: builtins.int
    ENDOFFILE_FIELD_NUMBER: builtins.int
    NEWOFFSET_FIELD_NUMBER: builtins.int
    data: builtins.bytes
    endOfFile: builtins.bool
    newOffset: builtins.int
    def __init__(
        self,
        *,
        data: builtins.bytes = ...,
        endOfFile: builtins.bool = ...,
        newOffset: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "data", b"data", "endOfFile", b"endOfFile", "newOffset", b"newOffset"
        ],
    ) -> None: ...

global___ReadOutputReply = ReadOutputReply

@typing.final
class GetProcessStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___GetProcessStatusRequest = GetProcessStatusRequest

@typing.final
class GetProcessStatusReply(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROCESSCOUNT_FIELD_NUMBER: builtins.int
    TOTALMEMORY_FIELD_NUMBER: builtins.int
    TOTALDATA_FIELD_NUMBER: builtins.int
    TOTALSHARED_FIELD_NUMBER: builtins.int
    TOTALRESIDENT_FIELD_NUMBER: builtins.int
    CPUUSER_FIELD_NUMBER: builtins.int
    CPUSYSTEM_FIELD_NUMBER: builtins.int
    CPUIDLE_FIELD_NUMBER: builtins.int
    CPUIOWAIT_FIELD_NUMBER: builtins.int
    MEMTOTAL_FIELD_NUMBER: builtins.int
    MEMAVAILABLE_FIELD_NUMBER: builtins.int
    MEMFREE_FIELD_NUMBER: builtins.int
    MEMPRESSURESOMEAVG10_FIELD_NUMBER: builtins.int
    MEMPRESSUREFULLAVG10_FIELD_NUMBER: builtins.int
    processCount: builtins.int
    totalMemory: builtins.int
    totalData: builtins.int
    totalShared: builtins.int
    totalResident: builtins.int
    cpuUser: builtins.int
    """CPU stats from /proc/stat (in jiffies, compute delta for %)"""
    cpuSystem: builtins.int
    cpuIdle: builtins.int
    cpuIowait: builtins.int
    memTotal: builtins.int
    """System memory from /proc/meminfo (in bytes)"""
    memAvailable: builtins.int
    memFree: builtins.int
    memPressureSomeAvg10: builtins.int
    """Memory pressure from /proc/pressure/memory (percentage * 100, -1 if unavailable)"""
    memPressureFullAvg10: builtins.int
    def __init__(
        self,
        *,
        processCount: builtins.int = ...,
        totalMemory: builtins.int = ...,
        totalData: builtins.int = ...,
        totalShared: builtins.int = ...,
        totalResident: builtins.int = ...,
        cpuUser: builtins.int = ...,
        cpuSystem: builtins.int = ...,
        cpuIdle: builtins.int = ...,
        cpuIowait: builtins.int = ...,
        memTotal: builtins.int = ...,
        memAvailable: builtins.int = ...,
        memFree: builtins.int = ...,
        memPressureSomeAvg10: builtins.int = ...,
        memPressureFullAvg10: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "cpuIdle",
            b"cpuIdle",
            "cpuIowait",
            b"cpuIowait",
            "cpuSystem",
            b"cpuSystem",
            "cpuUser",
            b"cpuUser",
            "memAvailable",
            b"memAvailable",
            "memFree",
            b"memFree",
            "memPressureFullAvg10",
            b"memPressureFullAvg10",
            "memPressureSomeAvg10",
            b"memPressureSomeAvg10",
            "memTotal",
            b"memTotal",
            "processCount",
            b"processCount",
            "totalData",
            b"totalData",
            "totalMemory",
            b"totalMemory",
            "totalResident",
            b"totalResident",
            "totalShared",
            b"totalShared",
        ],
    ) -> None: ...

global___GetProcessStatusReply = GetProcessStatusReply
