# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sparklespray import pb_pb2 as sparklespray_dot_pb__pb2


class MonitorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadOutput = channel.unary_unary(
                '/Monitor/ReadOutput',
                request_serializer=sparklespray_dot_pb__pb2.ReadOutputRequest.SerializeToString,
                response_deserializer=sparklespray_dot_pb__pb2.ReadOutputReply.FromString,
                )
        self.GetProcessStatus = channel.unary_unary(
                '/Monitor/GetProcessStatus',
                request_serializer=sparklespray_dot_pb__pb2.GetProcessStatusRequest.SerializeToString,
                response_deserializer=sparklespray_dot_pb__pb2.GetProcessStatusReply.FromString,
                )


class MonitorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReadOutput(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadOutput,
                    request_deserializer=sparklespray_dot_pb__pb2.ReadOutputRequest.FromString,
                    response_serializer=sparklespray_dot_pb__pb2.ReadOutputReply.SerializeToString,
            ),
            'GetProcessStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcessStatus,
                    request_deserializer=sparklespray_dot_pb__pb2.GetProcessStatusRequest.FromString,
                    response_serializer=sparklespray_dot_pb__pb2.GetProcessStatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Monitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Monitor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReadOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Monitor/ReadOutput',
            sparklespray_dot_pb__pb2.ReadOutputRequest.SerializeToString,
            sparklespray_dot_pb__pb2.ReadOutputReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProcessStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Monitor/GetProcessStatus',
            sparklespray_dot_pb__pb2.GetProcessStatusRequest.SerializeToString,
            sparklespray_dot_pb__pb2.GetProcessStatusReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
