# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sparklespray/pb.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sparklespray/pb.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x15sparklespray/pb.proto\"A\n\x11ReadOutputRequest\x12\x0e\n\x06taskId\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x03\"E\n\x0fReadOutputReply\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x11\n\tendOfFile\x18\x02 \x01(\x08\x12\x11\n\tnewOffset\x18\x03 \x01(\x03\"\x19\n\x17GetProcessStatusRequest\"\x81\x01\n\x15GetProcessStatusReply\x12\x14\n\x0cprocessCount\x18\x01 \x01(\x05\x12\x13\n\x0btotalMemory\x18\x02 \x01(\x03\x12\x11\n\ttotalData\x18\x03 \x01(\x03\x12\x13\n\x0btotalShared\x18\x04 \x01(\x03\x12\x15\n\rtotalResident\x18\x05 \x01(\x03\x32\x87\x01\n\x07Monitor\x12\x34\n\nReadOutput\x12\x12.ReadOutputRequest\x1a\x10.ReadOutputReply\"\x00\x12\x46\n\x10GetProcessStatus\x12\x18.GetProcessStatusRequest\x1a\x16.GetProcessStatusReply\"\x00\x62\x06proto3')
)




_READOUTPUTREQUEST = _descriptor.Descriptor(
  name='ReadOutputRequest',
  full_name='ReadOutputRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='taskId', full_name='ReadOutputRequest.taskId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='ReadOutputRequest.size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='offset', full_name='ReadOutputRequest.offset', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=90,
)


_READOUTPUTREPLY = _descriptor.Descriptor(
  name='ReadOutputReply',
  full_name='ReadOutputReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='ReadOutputReply.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='endOfFile', full_name='ReadOutputReply.endOfFile', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='newOffset', full_name='ReadOutputReply.newOffset', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=161,
)


_GETPROCESSSTATUSREQUEST = _descriptor.Descriptor(
  name='GetProcessStatusRequest',
  full_name='GetProcessStatusRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=188,
)


_GETPROCESSSTATUSREPLY = _descriptor.Descriptor(
  name='GetProcessStatusReply',
  full_name='GetProcessStatusReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='processCount', full_name='GetProcessStatusReply.processCount', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalMemory', full_name='GetProcessStatusReply.totalMemory', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalData', full_name='GetProcessStatusReply.totalData', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalShared', full_name='GetProcessStatusReply.totalShared', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalResident', full_name='GetProcessStatusReply.totalResident', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=320,
)

DESCRIPTOR.message_types_by_name['ReadOutputRequest'] = _READOUTPUTREQUEST
DESCRIPTOR.message_types_by_name['ReadOutputReply'] = _READOUTPUTREPLY
DESCRIPTOR.message_types_by_name['GetProcessStatusRequest'] = _GETPROCESSSTATUSREQUEST
DESCRIPTOR.message_types_by_name['GetProcessStatusReply'] = _GETPROCESSSTATUSREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReadOutputRequest = _reflection.GeneratedProtocolMessageType('ReadOutputRequest', (_message.Message,), dict(
  DESCRIPTOR = _READOUTPUTREQUEST,
  __module__ = 'sparklespray.pb_pb2'
  # @@protoc_insertion_point(class_scope:ReadOutputRequest)
  ))
_sym_db.RegisterMessage(ReadOutputRequest)

ReadOutputReply = _reflection.GeneratedProtocolMessageType('ReadOutputReply', (_message.Message,), dict(
  DESCRIPTOR = _READOUTPUTREPLY,
  __module__ = 'sparklespray.pb_pb2'
  # @@protoc_insertion_point(class_scope:ReadOutputReply)
  ))
_sym_db.RegisterMessage(ReadOutputReply)

GetProcessStatusRequest = _reflection.GeneratedProtocolMessageType('GetProcessStatusRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPROCESSSTATUSREQUEST,
  __module__ = 'sparklespray.pb_pb2'
  # @@protoc_insertion_point(class_scope:GetProcessStatusRequest)
  ))
_sym_db.RegisterMessage(GetProcessStatusRequest)

GetProcessStatusReply = _reflection.GeneratedProtocolMessageType('GetProcessStatusReply', (_message.Message,), dict(
  DESCRIPTOR = _GETPROCESSSTATUSREPLY,
  __module__ = 'sparklespray.pb_pb2'
  # @@protoc_insertion_point(class_scope:GetProcessStatusReply)
  ))
_sym_db.RegisterMessage(GetProcessStatusReply)



_MONITOR = _descriptor.ServiceDescriptor(
  name='Monitor',
  full_name='Monitor',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=323,
  serialized_end=458,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReadOutput',
    full_name='Monitor.ReadOutput',
    index=0,
    containing_service=None,
    input_type=_READOUTPUTREQUEST,
    output_type=_READOUTPUTREPLY,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetProcessStatus',
    full_name='Monitor.GetProcessStatus',
    index=1,
    containing_service=None,
    input_type=_GETPROCESSSTATUSREQUEST,
    output_type=_GETPROCESSSTATUSREPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONITOR)

DESCRIPTOR.services_by_name['Monitor'] = _MONITOR

# @@protoc_insertion_point(module_scope)
