// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type ReadOutputRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	Size                 int32    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Offset               int64    `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOutputRequest) Reset()         { *m = ReadOutputRequest{} }
func (m *ReadOutputRequest) String() string { return proto.CompactTextString(m) }
func (*ReadOutputRequest) ProtoMessage()    {}
func (*ReadOutputRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{0}
}

func (m *ReadOutputRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOutputRequest.Unmarshal(m, b)
}
func (m *ReadOutputRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOutputRequest.Marshal(b, m, deterministic)
}
func (m *ReadOutputRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOutputRequest.Merge(m, src)
}
func (m *ReadOutputRequest) XXX_Size() int {
	return xxx_messageInfo_ReadOutputRequest.Size(m)
}
func (m *ReadOutputRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOutputRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOutputRequest proto.InternalMessageInfo

func (m *ReadOutputRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *ReadOutputRequest) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ReadOutputRequest) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

// The response message containing the greetings
type ReadOutputReply struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	EndOfFile            bool     `protobuf:"varint,2,opt,name=endOfFile,proto3" json:"endOfFile,omitempty"`
	NewOffset            int64    `protobuf:"varint,3,opt,name=newOffset,proto3" json:"newOffset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadOutputReply) Reset()         { *m = ReadOutputReply{} }
func (m *ReadOutputReply) String() string { return proto.CompactTextString(m) }
func (*ReadOutputReply) ProtoMessage()    {}
func (*ReadOutputReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{1}
}

func (m *ReadOutputReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadOutputReply.Unmarshal(m, b)
}
func (m *ReadOutputReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadOutputReply.Marshal(b, m, deterministic)
}
func (m *ReadOutputReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadOutputReply.Merge(m, src)
}
func (m *ReadOutputReply) XXX_Size() int {
	return xxx_messageInfo_ReadOutputReply.Size(m)
}
func (m *ReadOutputReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadOutputReply.DiscardUnknown(m)
}

var xxx_messageInfo_ReadOutputReply proto.InternalMessageInfo

func (m *ReadOutputReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ReadOutputReply) GetEndOfFile() bool {
	if m != nil {
		return m.EndOfFile
	}
	return false
}

func (m *ReadOutputReply) GetNewOffset() int64 {
	if m != nil {
		return m.NewOffset
	}
	return 0
}

type GetProcessStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProcessStatusRequest) Reset()         { *m = GetProcessStatusRequest{} }
func (m *GetProcessStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetProcessStatusRequest) ProtoMessage()    {}
func (*GetProcessStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{2}
}

func (m *GetProcessStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProcessStatusRequest.Unmarshal(m, b)
}
func (m *GetProcessStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProcessStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetProcessStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProcessStatusRequest.Merge(m, src)
}
func (m *GetProcessStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetProcessStatusRequest.Size(m)
}
func (m *GetProcessStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProcessStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetProcessStatusRequest proto.InternalMessageInfo

type GetProcessStatusReply struct {
	ProcessCount         int32    `protobuf:"varint,1,opt,name=processCount,proto3" json:"processCount,omitempty"`
	TotalMemory          int64    `protobuf:"varint,2,opt,name=totalMemory,proto3" json:"totalMemory,omitempty"`
	TotalData            int64    `protobuf:"varint,3,opt,name=totalData,proto3" json:"totalData,omitempty"`
	TotalShared          int64    `protobuf:"varint,4,opt,name=totalShared,proto3" json:"totalShared,omitempty"`
	TotalResident        int64    `protobuf:"varint,5,opt,name=totalResident,proto3" json:"totalResident,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetProcessStatusReply) Reset()         { *m = GetProcessStatusReply{} }
func (m *GetProcessStatusReply) String() string { return proto.CompactTextString(m) }
func (*GetProcessStatusReply) ProtoMessage()    {}
func (*GetProcessStatusReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_f80abaa17e25ccc8, []int{3}
}

func (m *GetProcessStatusReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetProcessStatusReply.Unmarshal(m, b)
}
func (m *GetProcessStatusReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetProcessStatusReply.Marshal(b, m, deterministic)
}
func (m *GetProcessStatusReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetProcessStatusReply.Merge(m, src)
}
func (m *GetProcessStatusReply) XXX_Size() int {
	return xxx_messageInfo_GetProcessStatusReply.Size(m)
}
func (m *GetProcessStatusReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetProcessStatusReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetProcessStatusReply proto.InternalMessageInfo

func (m *GetProcessStatusReply) GetProcessCount() int32 {
	if m != nil {
		return m.ProcessCount
	}
	return 0
}

func (m *GetProcessStatusReply) GetTotalMemory() int64 {
	if m != nil {
		return m.TotalMemory
	}
	return 0
}

func (m *GetProcessStatusReply) GetTotalData() int64 {
	if m != nil {
		return m.TotalData
	}
	return 0
}

func (m *GetProcessStatusReply) GetTotalShared() int64 {
	if m != nil {
		return m.TotalShared
	}
	return 0
}

func (m *GetProcessStatusReply) GetTotalResident() int64 {
	if m != nil {
		return m.TotalResident
	}
	return 0
}

func init() {
	proto.RegisterType((*ReadOutputRequest)(nil), "ReadOutputRequest")
	proto.RegisterType((*ReadOutputReply)(nil), "ReadOutputReply")
	proto.RegisterType((*GetProcessStatusRequest)(nil), "GetProcessStatusRequest")
	proto.RegisterType((*GetProcessStatusReply)(nil), "GetProcessStatusReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MonitorClient is the client API for Monitor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MonitorClient interface {
	// Sends a greeting
	ReadOutput(ctx context.Context, in *ReadOutputRequest, opts ...grpc.CallOption) (*ReadOutputReply, error)
	GetProcessStatus(ctx context.Context, in *GetProcessStatusRequest, opts ...grpc.CallOption) (*GetProcessStatusReply, error)
}

type monitorClient struct {
	cc *grpc.ClientConn
}

func NewMonitorClient(cc *grpc.ClientConn) MonitorClient {
	return &monitorClient{cc}
}

func (c *monitorClient) ReadOutput(ctx context.Context, in *ReadOutputRequest, opts ...grpc.CallOption) (*ReadOutputReply, error) {
	out := new(ReadOutputReply)
	err := c.cc.Invoke(ctx, "/Monitor/ReadOutput", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *monitorClient) GetProcessStatus(ctx context.Context, in *GetProcessStatusRequest, opts ...grpc.CallOption) (*GetProcessStatusReply, error) {
	out := new(GetProcessStatusReply)
	err := c.cc.Invoke(ctx, "/Monitor/GetProcessStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MonitorServer is the server API for Monitor service.
type MonitorServer interface {
	// Sends a greeting
	ReadOutput(context.Context, *ReadOutputRequest) (*ReadOutputReply, error)
	GetProcessStatus(context.Context, *GetProcessStatusRequest) (*GetProcessStatusReply, error)
}

func RegisterMonitorServer(s *grpc.Server, srv MonitorServer) {
	s.RegisterService(&_Monitor_serviceDesc, srv)
}

func _Monitor_ReadOutput_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadOutputRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).ReadOutput(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Monitor/ReadOutput",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).ReadOutput(ctx, req.(*ReadOutputRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Monitor_GetProcessStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProcessStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MonitorServer).GetProcessStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Monitor/GetProcessStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MonitorServer).GetProcessStatus(ctx, req.(*GetProcessStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Monitor_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Monitor",
	HandlerType: (*MonitorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadOutput",
			Handler:    _Monitor_ReadOutput_Handler,
		},
		{
			MethodName: "GetProcessStatus",
			Handler:    _Monitor_GetProcessStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb.proto",
}

func init() { proto.RegisterFile("pb.proto", fileDescriptor_f80abaa17e25ccc8) }

var fileDescriptor_f80abaa17e25ccc8 = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcd, 0x4e, 0x02, 0x31,
	0x14, 0x85, 0xa9, 0xfc, 0x08, 0x57, 0x8c, 0xd8, 0x44, 0xac, 0xc4, 0xc5, 0xa4, 0x71, 0xc1, 0x6a,
	0x16, 0xea, 0x1b, 0x68, 0x30, 0x2e, 0x08, 0xa6, 0x2c, 0x5c, 0x17, 0x7b, 0x89, 0x13, 0x71, 0x3a,
	0x4e, 0xef, 0xc4, 0xe0, 0x0b, 0xf8, 0x60, 0xbe, 0x98, 0x69, 0x99, 0xc0, 0x00, 0xba, 0xeb, 0xf9,
	0xda, 0x7b, 0x72, 0xee, 0x99, 0x81, 0x76, 0x36, 0x8b, 0xb3, 0xdc, 0x92, 0x95, 0xcf, 0x70, 0xaa,
	0x50, 0x9b, 0x49, 0x41, 0x59, 0x41, 0x0a, 0x3f, 0x0a, 0x74, 0xc4, 0xfb, 0xd0, 0x22, 0xed, 0xde,
	0x1e, 0x8d, 0x60, 0x11, 0x1b, 0x76, 0x54, 0xa9, 0x38, 0x87, 0x86, 0x4b, 0xbe, 0x50, 0x1c, 0x44,
	0x6c, 0xd8, 0x54, 0xe1, 0xec, 0xdf, 0xda, 0xf9, 0xdc, 0x21, 0x89, 0x7a, 0xc4, 0x86, 0x75, 0x55,
	0x2a, 0xa9, 0xe1, 0xa4, 0x6a, 0x9c, 0x2d, 0x96, 0x7e, 0xdc, 0x68, 0xd2, 0xc1, 0xb4, 0xab, 0xc2,
	0x99, 0x5f, 0x42, 0x07, 0x53, 0x33, 0x99, 0x8f, 0x92, 0xc5, 0xca, 0xb7, 0xad, 0x36, 0xc0, 0xdf,
	0xa6, 0xf8, 0x39, 0xa9, 0xfa, 0x6f, 0x80, 0xbc, 0x80, 0xf3, 0x07, 0xa4, 0xa7, 0xdc, 0xbe, 0xa0,
	0x73, 0x53, 0xd2, 0x54, 0xb8, 0x72, 0x03, 0xf9, 0xc3, 0xe0, 0x6c, 0xff, 0xce, 0x87, 0x90, 0xd0,
	0xcd, 0x56, 0xf4, 0xce, 0x16, 0x29, 0x85, 0x30, 0x4d, 0xb5, 0xc5, 0x78, 0x04, 0x47, 0x64, 0x49,
	0x2f, 0xc6, 0xf8, 0x6e, 0xf3, 0x65, 0x88, 0x55, 0x57, 0x55, 0xe4, 0x83, 0x05, 0x79, 0xef, 0xf7,
	0x29, 0x83, 0xad, 0xc1, 0x7a, 0x7e, 0xfa, 0xaa, 0x73, 0x34, 0xa2, 0x51, 0x99, 0x5f, 0x21, 0x7e,
	0x05, 0xc7, 0x41, 0x2a, 0x74, 0x89, 0xc1, 0x94, 0x44, 0x33, 0xbc, 0xd9, 0x86, 0xd7, 0xdf, 0x0c,
	0x0e, 0xc7, 0x36, 0x4d, 0xc8, 0xe6, 0xfc, 0x16, 0x60, 0xd3, 0x27, 0xe7, 0xf1, 0xde, 0x57, 0x1b,
	0xf4, 0xe2, 0x9d, 0xc2, 0x65, 0x8d, 0x8f, 0xa0, 0xb7, 0x5b, 0x03, 0x17, 0xf1, 0x3f, 0xad, 0x0d,
	0xfa, 0xf1, 0x9f, 0x9d, 0xc9, 0xda, 0xac, 0x15, 0xfe, 0x96, 0x9b, 0xdf, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x66, 0x2d, 0x00, 0x3b, 0x39, 0x02, 0x00, 0x00,
}
