#!/usr/bin/python
import urllib2
import os

nomad_config_template = """
bind_addr = "0.0.0.0"
data_dir = "/nomad_datadir"

advertise {{
  # We need to specify our host's IP because we can't
  # advertise 0.0.0.0 to other nodes in our cluster.
  rpc = "{ipaddr}:4647"
  serf = "{ipaddr}:4648"
}}


server {{
  enabled = true
  bootstrap_expect = 1
}}
"""

ipaddr = urllib2.urlopen("http://169.254.169.254/latest/meta-data/local-ipv4").read()
fd = open("/etc/nomad/server.conf", "wt")
fd.write(nomad_config_template.format(ipaddr=ipaddr))
fd.close()

os.execl("/usr/bin/nomad", "/usr/bin/nomad", "agent", "-config", "/etc/nomad/server.conf")

