#!/usr/bin/python
import urllib2
import os

consul_config_template = """
{{
 "data_dir" : "/consul_datadir",
 "addresses": {{
    "https": "0.0.0.0"
  }},
  "advertise_addr": "{ipaddr}",
  "server": true,
  "bootstrap_expect": 1
}}
"""

ipaddr = urllib2.urlopen("http://169.254.169.254/latest/meta-data/local-ipv4").read()
fd = open("/etc/consul/server.json", "wt")
fd.write(consul_config_template.format(ipaddr=ipaddr))
fd.close()

os.execl("/usr/bin/consul", "/usr/bin/consul", "agent", "-config-file", "/etc/consul/server.json")

