name: build

on:
  push:
    paths:
      - "v100/**"
      - ".github/workflows/build.yaml"
  pull_request:
    paths:
      - "v100/**"
      - ".github/workflows/build.yaml"

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: v100
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: v100/go.mod
      - name: Build
        run: go build ./...
      - name: Test
        run: go test ./...
