name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v go/src/github.com/broadinstitute/kubequeconsume/cli/main.go

    - name: Test
      run: go test -v go/src/github.com/broadinstitute/kubequeconsume/...
      
