name: Go

on:
  push:
      paths:
         - "**/*.go"
         - .github/workflows/go.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build everything
      run: cd go/src/github.com/broadinstitute/kubequeconsume && go build -v ./...

    - name: build executable
      run: bash scripts/build-static-exe.sh

#    - name: Test
#      run: cd go/src/github.com/broadinstitute/kubequeconsume && go test -v ./...
      
